export type RoadmapBlock = {
  id: string;
  title: string;
  hint: string;
  details: string[];
};

export type CourseEntry = {
  slug: string;
  title: string;
  category: string;
  description: string;
  roadmapBlocks: RoadmapBlock[];
};

const civilEngineeringPrograms = [
  "Masters in CPM & BIM Modeller|6 Months|Offline Classes",
  "Professional Diploma in CPM with BIM Modeller|3 Months|Offline Classes",
  "Certified Estimation & QC Engineer|3 Months|Offline Classes",
  "Professional Diploma in Interior Designing|6 Months|Offline Classes",
];

const civilRoadmapBlocks: RoadmapBlock[] = [
  {
    id: "featured-courses",
    title: "Featured Programs",
    hint: "Specialized civil engineering tracks",
    details: civilEngineeringPrograms,
  },
  {
    id: "job-roles",
    title: "Job Roles",
    hint: "Career outcomes",
    details: [
      "Site Engineer",
      "Construction Project Manager",
      "Planning Engineer",
      "Quantity Surveyor",
      "Cost Estimator",
      "BIM Modeller",
      "BIM Coordinator",
      "BMS Engineer",
      "Structural Engineer",
      "QA/QC Engineer",
      "Construction Safety Officer",
      "QC Laboratory Technician",
      "NDT QC Inspector",
      "Interior Designer",
      "3D Visualizer",
    ],
  },
  {
    id: "what-we-offer",
    title: "What We Offer",
    hint: "Training support",
    details: [
      "Industry-standard software training (AutoCAD, Revit, MS Project)",
      "Real-world project case studies and simulations",
      "Expert mentorship from experienced civil engineers",
      "Hands-on lab sessions with latest tools",
      "Placement assistance and interview preparation",
    ],
  },
  {
    id: "did-you-know",
    title: "Did You Know?",
    hint: "Industry insights",
    details: [
      "BIM adoption growing rapidly in construction sector",
      "High demand for certified estimation professionals",
      "Interior design market expanding with infrastructure growth",
      "CPM skills essential for modern project management",
    ],
  },
];

const defaultRoadmapBlocks = (course: string): RoadmapBlock[] => [
  {
    id: "featured-courses",
    title: "Featured Courses",
    hint: "Program options",
    details: [
      `${course} fast-track modules`,
      "Professional diploma and certification tracks",
      "Beginner-to-advanced pathway options",
    ],
  },
  {
    id: "job-roles",
    title: "Job Roles",
    hint: "Career outcomes",
    details: [
      "Entry-level and intermediate role pathways",
      "Domain-specific technical career tracks",
      "Industry-oriented role mapping",
    ],
  },
  {
    id: "what-we-offer",
    title: "What We Offer",
    hint: "Training support",
    details: [
      "Hands-on lab sessions and guided practice",
      "Trainer mentorship and practical assignments",
      "Project-based implementation support",
    ],
  },
  {
    id: "did-you-know",
    title: "Did You Know?",
    hint: "Insights",
    details: [
      "Industry demand trends for this domain",
      "Skill-stack combinations for better opportunities",
      "Roadmap checkpoints to track your progress",
    ],
  },
];

export const courses: CourseEntry[] = [
  {
    slug: "civil-course-in-kochi",
    title: "Civil Engineering Course",
    category: "Civil Engineering",
    description: "SMEC Training offers specialized civil engineering courses focused on practical skills and industry standards. Led by experienced professionals, the programs cover structural design, construction management, and sustainable infrastructure. Combining theory with hands-on experience, the training enhances technical proficiency and prepares students for successful, long-term careers in the competitive construction and infrastructure sectors.",
    roadmapBlocks: civilRoadmapBlocks,
  },
  {
    slug: "industrial-automation-course-in-kochi",
    title: "Industrial Automation",
    category: "Automation",
    description:
      "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in industrial automation, ensuring their curriculum is aligned with real-world applications. We are the robust automation sector teams that provide hands-on, industry-focused training with a notable focus on practical skills, taught by seasoned specialists in the field of industrial automation, making graduates extremely employable.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized automation tracks",
        details: [
          "Masters In Industrial Automation & Instrumentation|9 Months|Offline Classes",
          "Professional Diploma In Industrial Automation|6 Months|Offline Classes",
          "Professional Diploma In Instrumentation Technician|6 Months|Offline Classes",
          "Certified Industrial Automation Engineer|3 Months|Offline Classes",
          "Certified Industrial Instrumentation Engineer|3 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Automation Engineer",
          "Instrumentation Engineer",
          "PLC Programmer",
          "Control Systems Engineer",
          "SCADA Engineer",
          "Maintenance Engineer",
          "Instrumentation Technician",
          "Automation Technician",
          "Instrumentation & Control Specialist",
          "DCS operator & Maintenance Engineer",
          "Project Manager",
          "Process Control Engineer",
          "Electrical Engineer",
          "Field Service Engineer",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with real industrial equipment",
          "Curriculum aligned with current industry standards",
          "Training by seasoned automation specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Lab sessions with PLCs, SCADA, and robotics systems",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive industry experience",
          "Industrial automation skills are in high demand across manufacturing sectors",
          "Industry 4.0 is transforming traditional manufacturing processes",
          "Our graduates benefit from real-world curriculum developed by automation experts",
          "Practical skills training significantly increases employability in automation",
        ],
      },
    ],
  },
  {
    slug: "oil-and-gas-course-in-kochi",
    title: "Oil and Gas",
    category: "Oil and Gas",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in the oil and gas industry, ensuring their curriculum is aligned with real-world applications. We have a strong team of industry experts who provide hands-on, industry-focused training with a notable focus on practical skills. Our courses are taught by seasoned specialists in the field, making graduates highly employable in the oil and gas sector.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized oil and gas tracks",
        details: [
          "Master in Oil & Gas Instrumentation Technician|12 Months|Offline Classes",
          "Professional Diploma in Oil & Gas Technician|8 Months|Offline Classes",
          "Professional Diploma in Oil & Gas with Project Management|6 Months|Offline Classes",
          "Certified Quality & Safety Engineer|12 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Project Engineer",
          "Piping Engineer",
          "Planning Engineer",
          "Site Engineer",
          "Mechanical Supervisor",
          "Piping Supervisor",
          "Piping Foreman",
          "QC Engineer",
          "QA Engineer",
          "Welding Inspector",
          "QC Inspector",
          "NDT Technician",
          "NDT Inspector",
          "Safety Officer",
          "Instrumentation Engineer",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with industry-standard equipment",
          "Curriculum aligned with oil and gas industry standards",
          "Training by seasoned oil and gas specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Process simulation and safety training",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive oil and gas experience",
          "Oil and gas sector offers diverse career opportunities globally",
          "Process safety skills are critical in the energy industry",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in oil and gas",
        ],
      },
    ],
  },
  {
    slug: "embedded-systems-course-in-kochi",
    title: "Embedded Systems Course",
    category: "Electronics",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in embedded systems, ensuring their curriculum is aligned with real-world applications. We are a robust embedded systems team that provides hands-on, industry-focused training with a strong emphasis on practical skills. Our courses are taught by seasoned specialists in the field of embedded systems, making graduates highly employable.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized embedded systems tracks",
        details: [
          "Masters in Embedded Firmware with AutoSAR|9 Months|Offline Classes",
          "Professional Diploma in Embedded Firmware|6 Months|Offline Classes",
          "Certified Embedded Firmware Engineer|3 Months|Offline Classes",
          "Certified VLSI Engineer|3 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Embedded Service Engineer",
          "Electronics Design Engineer",
          "Embedded Engineer",
          "IoT Engineer",
          "Quality Control Engineer",
          "FPGA Engineer",
          "RTL Design Engineer",
          "Embedded Test Engineer",
          "Embedded Sales Engineer",
          "Design Verification Engineer",
          "Embedded Hardware Engineer",
          "Automotive Electronics Engineer",
          "Embedded Software Engineer",
          "Firmware Engineer",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with real embedded hardware",
          "Curriculum aligned with industry standards",
          "Training by seasoned embedded systems specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Lab sessions with microcontrollers and development boards",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive embedded systems experience",
          "Embedded systems are the backbone of modern electronics",
          "IoT and smart devices are driving demand for embedded engineers",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in embedded systems",
        ],
      },
    ],
  },
  {
    slug: "mep-course-in-kochi",
    title: "MEP Course",
    category: "Engineering",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in Mechanical, Electrical, and Plumbing (MEP), ensuring their curriculum is aligned with real-world applications. We are a robust team in the MEP sector, providing hands-on, industry-focused training with a strong emphasis on practical skills. Our courses are taught by seasoned specialists in the field of MEP, making graduates highly employable in the industry.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized MEP tracks",
        details: [
          "Professional Diploma in MEP & BIM Engineer|6 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "BIM Mechanical/ Electrical Engineer",
          "MEP Design Engineer",
          "MEP Project Engineer",
          "Plumbing & Fire Fighting Engineer",
          "MEP Site Engineer/ Coordinator",
          "MEP Commissioning Engineer",
          "Electrical Engineer - HV/LV",
          "REVIT MEP Modeller",
          "MEP Estimator",
          "MEP Draftsman",
          "HVAC Engineer",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with industry-standard MEP tools",
          "Curriculum aligned with MEP industry standards",
          "Training by seasoned MEP specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Software training in AutoCAD MEP, Revit MEP, and design tools",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive MEP experience",
          "MEP systems account for a significant portion of building costs",
          "BIM integration is transforming MEP design and coordination",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in MEP",
        ],
      },
    ],
  },
  {
    slug: "industrial-safety-course-in-kochi",
    title: "Industrial Safety",
    category: "Safety",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in industrial safety, ensuring their curriculum is aligned with real-world applications. We have a strong team of industry experts who provide hands-on, industry-focused training with a notable focus on practical skills. Our courses are taught by seasoned specialists in the field of industrial safety, making graduates highly employable in the industry.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized safety tracks",
        details: [
          "Professional Diploma in Industrial Fire & Safety|6 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Safety Manager",
          "Safety Officer",
          "HSE Officer",
          "Fire Brigade",
          "Fire Watcher",
          "Fire Alarm Technician",
          "Fire Hydrant Technician",
        ],
      },
      {
        id: "job-areas",
        title: "Job Areas",
        hint: "Industry sectors",
        details: [
          "Construction",
          "Oil & Gas",
          "Manufacturing & Industrial",
          "Mining & Quarrying",
          "Transportation & Logistics",
          "Aviation & Aerospace",
          "Power Generation & Utilities",
          "Marine & Shipping",
          "Food & Beverage Processing",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with real safety scenarios",
          "Curriculum aligned with international safety standards",
          "Training by seasoned industrial safety specialists",
          "Real-world case studies and simulations",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Practical sessions on safety equipment and procedures",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive safety experience",
          "Industrial safety professionals are in high demand across all sectors",
          "Safety compliance is mandatory in modern industrial operations",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in safety roles",
        ],
      },
    ],
  },
  {
    slug: "bms-course-in-kochi",
    title: "BMS",
    category: "Automation",
    description: "Learning Building Management Systems (BMS) from SMEClabs provides industry-oriented training with hands-on experience in HVAC, lighting, security, fire safety, SCADA, PLCs, and IoT integration. Our globally recognized certifications, expert faculty, and live project-based learning make students job-ready. SMEClabs offers flexible learning modes (online/offline/hybrid) and has strong industry tie-ups for placement assistance in India and abroad.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized BMS tracks",
        details: [
          "Professional Diploma in BMS Technician|6 Months|Offline Classes",
          "Certified BMS Engineer|3 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "BMS Technician",
          "BMS Operator",
          "Facility Technician",
          "Control Room Operator",
          "ELV Technician",
          "CCTV Technician",
          "Fire Alarm Technician",
          "BMS Engineer",
          "Automation Engineer",
          "Project Manager",
          "BMS Design Engineer",
          "BMS Support Specialist",
          "Facility Manager",
          "Project Engineer",
          "Technical Sales Engineer",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with HVAC, lighting, security, and fire safety systems",
          "Live project-based learning with real BMS implementations",
          "Expert faculty with industry experience",
          "Globally recognized certifications",
          "Flexible learning modes: online, offline, and hybrid",
          "Strong industry tie-ups for placement in India and abroad",
          "Training on SCADA, PLCs, and IoT integration",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "Smart buildings are transforming facility management worldwide",
          "BMS professionals are in high demand in commercial and industrial sectors",
          "IoT integration is revolutionizing building automation",
          "Energy management through BMS can reduce operational costs by 30%",
          "Our flexible learning modes accommodate working professionals",
        ],
      },
    ],
  },
  {
    slug: "software-testing-course-in-kochi",
    title: "Software Testing",
    category: "IT",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in Software Testing, ensuring their curriculum is aligned with real-world applications. We are a robust software testing team that provides hands-on, industry-focused training with a strong emphasis on practical skills. Our courses are taught by seasoned specialists in the field of Software Testing, making graduates highly employable.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized testing tracks",
        details: [
          "Advanced Software Testing Engineer|12 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Manual Tester",
          "Automation Test Engineer",
          "Performance Tester",
          "API Tester",
          "QA Analyst / Engineer",
          "Test Lead / Test Manager",
          "Mobile Application Tester",
          "Security Tester",
          "Usability Tester",
          "Test Architect",
          "Quality Assurance Consultant",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with real testing projects",
          "Curriculum aligned with industry testing standards",
          "Training by seasoned software testing specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Training on popular testing tools and frameworks",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive software testing experience",
          "Software testing is one of the most in-demand IT skills",
          "Automation testing skills significantly increase career opportunities",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in QA roles",
        ],
      },
    ],
  },
  {
    slug: "python-course-in-kochi",
    title: "Python Full Stack Development",
    category: "Software Development",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in Python full-stack development, ensuring their curriculum is aligned with real-world applications. We are a robust software development team that provides hands-on, industry-focused training with a strong emphasis on practical skills. Our courses are taught by seasoned specialists in the field of Python full-stack development, making graduates highly employable.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized Python tracks",
        details: [
          "Master in Full Stack Web & APP Development|12 Months|Offline Classes",
          "Professional Diploma in Full stack Web & APP Development|8 Months|Offline Classes",
          "Certifed Python Fullstack Developer|6 Months|Offline Classes",
          "Certified MEARN Stack Developer|12 Months|Offline Classes",
          "Certified UI/UX Developer|12 Months|Offline Classes",
          "Certified Flutter Developer|12 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Full Stack Developer",
          "Python Developer",
          "Frontend Developer",
          "Backend Developer",
          "Software Engineer",
          "Software Developer",
          "Django Developer",
          "React Developer",
          "SQL Developer",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with real development projects",
          "Curriculum aligned with industry development standards",
          "Training by seasoned Python full-stack specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Training on popular frameworks and deployment tools",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive software development experience",
          "Python is one of the most in-demand programming languages",
          "Full-stack developers are highly sought after in the job market",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in software development",
        ],
      },
    ],
  },
  {
    slug: "data-science-course-in-kochi",
    title: "Data Science Course",
    category: "Data Science",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in Data Science, ensuring their curriculum is aligned with real-world applications. We are a robust data science team that provides hands-on, industry-focused training with a strong emphasis on practical skills. Our courses are taught by seasoned specialists in the field of Data Science, making graduates highly employable.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized data science tracks",
        details: [
          "Masters in Data Science with AI & ML|12 Months|Offline Classes",
          "Professional Certification in AI & ML with Data Science|8 Months|Offline Classes",
          "Certified Data Analytics Engineer|6 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Data Scientist",
          "Data Analyst",
          "Machine Learning Engineer",
          "Machine Learning Specialists",
          "Business Analyst",
          "Big Data Engineer",
          "Hadoop/Spark Specialist",
          "AI Engineer",
          "NLP Engineer",
          "AI Specialists",
          "Computer Vision Engineer",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with real data science projects",
          "Curriculum aligned with industry data science standards",
          "Training by seasoned data science specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Training on popular data science tools and frameworks",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive data science experience",
          "Data Science is one of the fastest-growing career fields",
          "AI and ML skills are in extremely high demand across industries",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in data science",
        ],
      },
    ],
  },
  {
    slug: "networking-course-in-kochi",
    title: "Networking Course",
    category: "Networking",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in networking, cloud computing and cybersecurity, ensuring their curriculum is aligned with real-world applications. We have robust teams in the cybersecurity and networking sector that provide hands-on, industry-focused training with a strong emphasis on practical skills. Our courses are taught by seasoned specialists, making graduates highly employable in the field of networking, cloud computing and cybersecurity.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized networking tracks",
        details: [
          "Expert in Multi Cloud & Hybrid Infrastructure Management|12 Months|Offline Classes",
          "Professional Diploma in Cyber Security|8 Months|Offline Classes",
          "Professional Microsoft & Azure Cloud Architect|6 Months|Offline Classes",
          "Professional Linux & AWS Cloud Architect|6Months|Offline Classes",
          "Certified Networking Engineer (Windows)|6Months|Offline Classes",
          "Certified Networking Engineer (Linux)|6Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Network Engineer",
          "Security Operations Center (SOC) Analyst",
          "Network Security Engineer",
          "Network Operations Engineer",
          "Cloud Solutions Architect",
          "Cloud Engineer",
          "Systems Administrator",
          "Cloud Security Engineer",
          "Cybersecurity Analyst",
          "Incident Response Analyst",
          "IT Infrastructure Engineer",
          "Technical Support Engineer",
          "IT Consultant",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with real networking and cloud infrastructure",
          "Curriculum aligned with industry networking and security standards",
          "Training by seasoned networking and cybersecurity specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Training on AWS, Azure, Linux, Windows, and security tools",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive networking experience",
          "Cloud computing and cybersecurity are among the fastest-growing IT fields",
          "Multi-cloud skills are highly valued in modern enterprises",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in networking",
        ],
      },
    ],
  },
  {
    slug: "software-development-course-in-kochi",
    title: "Software Development",
    category: "IT",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in Full Stack Web & App Development, ensuring their curriculum is aligned with real-world applications. We are a robust software development team that provides hands-on, industry-focused training with a strong emphasis on practical skills. Our courses are taught by seasoned specialists in the field of Full Stack Web & App Development, making graduates highly employable.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized development tracks",
        details: [
          "Professional Diploma in Full Stack Web & APP Development|12 Months|Offline Classes",
          "Master in Full Stack Web & APP Development|8 Months|Offline Classes",
          "Certified UI UX Developer|6 Months|Offline Classes",
          "Certified Python Full Stack Developer|6Months|Offline Classes",
          "Certified MEARN Stack Developer|6Months|Offline Classes",
          "Certified Flutter Developer|6Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Full Stack Developer",
          "Python Developer",
          "Frontend Developer",
          "Backend Developer",
          "Software Engineer",
          "Software Developer",
          "React Developer",
          "Django Developer",
          "SQL Developer",
          "Flutter Developer",
          "Mobile App Developer",
          "Cross Platform Developer",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with real web and app development projects",
          "Curriculum aligned with industry development standards",
          "Training by seasoned full-stack development specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Training on popular frameworks and development tools",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive software development experience",
          "Full-stack developers are among the most sought-after professionals",
          "Mobile app development skills open doors to diverse opportunities",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in software development",
        ],
      },
    ],
  },
  {
    slug: "fintech-course-in-kochi",
    title: "Fintech Training",
    category: "Finance Technology",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in finance, accounting, and management, ensuring their curriculum is aligned with real-world applications. We have a strong team of industry experts who provide hands-on, industry-focused training with a notable focus on practical skills. Our courses are taught by seasoned specialists in the field, making graduates highly employable in finance, accounting, and management roles.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized fintech tracks",
        details: [
          "Professional Diploma in Corporate Accounting Management|12 Months|Offline Classes",
          "SAP Certified Application Associate (SAP S/4HANA Finance)|8 Months|Offline Classes",
          "SAP Certified Application Associate (SAP S/4HANA MM)|6 Months|Offline Classes",
          "Certified Indian & Foreign Accounting Professional|6Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Accountant",
          "Accounts Officer",
          "HR Associate",
          "Associate- Accounts",
          "MIS Executive",
          "Data Entry- Tally",
          "Tally Operator",
          "SAP Associate",
          "Finance Analyst",
          "Credit Analyst",
          "Auditor",
          "Financial Planner/Advisor",
          "Payroll Specialist",
          "Clerks",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with real finance and accounting scenarios",
          "Curriculum aligned with industry finance standards",
          "Training by seasoned finance and accounting specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "SAP certification preparation and support",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive finance experience",
          "SAP skills are highly valued in corporate finance roles",
          "Finance and accounting professionals are in constant demand",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in finance",
        ],
      },
    ],
  },
  {
    slug: "digital-marketing-course-in-kochi",
    title: "Digital Marketing",
    category: "Marketing",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in digital marketing, ensuring their curriculum is aligned with real-world applications. We have a strong team of digital marketing experts who provide hands-on, industry-focused training with a notable focus on practical skills. Our courses are taught by seasoned specialists in the field, making graduates highly employable in the digital marketing industry.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized digital marketing tracks",
        details: [
          "Professional Diploma in Digital Marketing with AI|6Months|Offline Classes",
          "Certified Digital Marketing Associate|3 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Digital Marketing Executive",
          "SEO Executive",
          "Social Media Executive",
          "PPC Specialist",
          "Growth Marketing Associate",
          "Copywriter (Entry Level)",
          "Search Engine Marketing (SEM) Associate",
          "Marketing Automation Associate",
          "Video Marketing Executive",
          "Marketing Coordinator",
          "Affiliate Marketer",
          "Content Writer (Digital Marketing)",
          "Blockchain Marketing Associate",
          "WordPress Developer (Junior Level)",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with real digital marketing campaigns",
          "Curriculum aligned with industry digital marketing standards",
          "Training by seasoned digital marketing specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Training on AI-powered marketing tools and platforms",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive digital marketing experience",
          "Digital marketing is one of the fastest-growing career fields",
          "AI is transforming digital marketing strategies and execution",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in digital marketing",
        ],
      },
    ],
  },
  {
    slug: "logistics-course-in-kochi",
    title: "Logistics Course",
    category: "Logistics",
    description: "SMEClabs is the training division of SMEC Automation Pvt. Ltd., a company with extensive experience in Shipping & Logistics, ensuring their curriculum is aligned with real world applications. We are a robust logistics and supply chain management team that provides hands-on, industry-focused training with a strong emphasis on practical skills. Our courses are taught by seasoned specialists in the field of Shipping & Logistics, making graduates highly employable.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized logistics tracks",
        details: [
          "PG Diploma in Digital Supply Chain Management with AI & Data Science|15 Months|Offline Classes",
          "PG Diploma in AI Supply Chain Management & Logistics|12 Months|Offline Classes",
          "Advanced Diploma in Supply Chain Management & Logistics|9 Months|Offline Classes",
          "Professional Diploma in Supply Chain Management & Logistics|6 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Logistics Coordinator",
          "Supply Chain Manager",
          "Inventory Control Manager",
          "Warehouse Manager",
          "Fleet Manager",
          "Marine Logistics Coordinator",
          "Shipping Coordinator",
          "Logistics Analyst",
          "Procurement Specialist",
          "Cold Chain Logistics Manager",
          "E-commerce Logistics Manager",
          "Freight Forwarder",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on training with real logistics and supply chain scenarios",
          "Curriculum aligned with industry shipping and logistics standards",
          "Training by seasoned shipping and logistics specialists",
          "Real-world project implementation experience",
          "Direct industry insights from SMEC Automation",
          "Placement assistance with industry connections",
          "Training on logistics management systems and tools",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "SMEClabs is backed by SMEC Automation's extensive logistics experience",
          "Logistics and supply chain management are critical to global trade",
          "E-commerce growth is driving demand for logistics professionals",
          "Our curriculum is developed by industry experts with real-world experience",
          "Practical skills training significantly increases employability in logistics",
        ],
      },
    ],
  },
  {
    slug: "graphic-design-and-film-editing-course",
    title: "Graphic Design and Film Editing Courses",
    category: "Creative Media",
    description: "SMEClabs in Kerala offers a comprehensive Graphic Design course designed for aspiring designers and creative professionals. The course covers key areas such as typography, color theory, branding, visual communication, layout design, and software tools like Adobe Photoshop, Illustrator, and InDesign. With flexible learning options including online, offline, and hybrid modes, students can choose the format that suits them best. SMEClabs also provides hands-on projects, portfolio development, and placement assistance to help students build a successful career in graphic design. Whether you're a beginner or looking to enhance your skills, SMEClabs delivers industry-relevant training in a supportive learning environment.",
    roadmapBlocks: [
      {
        id: "featured-courses",
        title: "Featured Programs",
        hint: "Specialized creative media tracks",
        details: [
          "Masters in Graphic Design and Film Editing with VFX|12 Months|Offline Classes",
          "Professional Diploma in Graphic Design and Film Editing|6 Months|Offline Classes",
          "Certified Graphic Design & Film Editing Specialist|3 Months|Offline Classes",
        ],
      },
      {
        id: "job-roles",
        title: "Job Roles",
        hint: "Career outcomes",
        details: [
          "Graphic Designer",
          "Brand Identity Designer",
          "UI/UX Designer",
          "Motion Graphic Designer",
          "Creative Director / Art Director",
          "Video Editor",
          "Film Editor",
          "Motion Graphics Artist",
          "VFX Artist (Visual Effects)",
          "Colorist",
          "Sound & Video Synchronization Specialist",
          "Multimedia Designer",
          "Graphic Designer + Video Editor",
          "Content Creator / Social Media Designer",
          "E-learning / Presentation Designer",
        ],
      },
      {
        id: "what-we-offer",
        title: "What We Offer",
        hint: "Training support",
        details: [
          "Hands-on projects and portfolio development",
          "Training on Adobe Photoshop, Illustrator, InDesign, and VFX tools",
          "Flexible learning modes: online, offline, and hybrid",
          "Industry-relevant curriculum covering typography, color theory, and branding",
          "Placement assistance to build a successful career",
          "Supportive learning environment for beginners and professionals",
          "Real-world visual communication and layout design training",
        ],
      },
      {
        id: "did-you-know",
        title: "Did You Know?",
        hint: "Industry insights",
        details: [
          "Graphic design and video editing are among the most in-demand creative skills",
          "VFX and motion graphics are transforming the media industry",
          "Portfolio development is crucial for landing creative jobs",
          "Our flexible learning modes accommodate working professionals",
          "Practical skills training significantly increases employability in creative fields",
        ],
      },
    ],
  },
];

export const coursesBySlug = new Map(courses.map((course) => [course.slug, course]));
